import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Marroqui from "@/components/Marroqui";
import Flex from "@/components/Marroqui/flex";
import BannerText from "@/components/BannerText";
import Accesorios from "@/components/Accesorios";
import Bolsos from "@/components/Bolsos";
import Cinturones from "@/components/Cinturones";
import BannerVideo from "@/components/bannerVideo";
import Devocion from "@/components/Devocion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const imagesPerPage = 2;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Wix+Madefor+Display&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className={styles.container}>
          <Header />
        <div className={styles.sticky} id="seccion1">
          <BannerVideo />
        </div>
        <div className={styles.sticky2}>
          <BannerText />
          <Flex />
          <Accesorios />
          <Bolsos />
          <Cinturones />
          <Devocion />
        </div>
      </div>
    </>
  );
}
